image: node:latest

stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

# build:
#   stage: build
#   script:
#     - yarn
#     - yarn build-prod

# lint:
#   stage: lint
#   script:
#     - yarn lint

# stylelint:
#   stage: lint
#   script:
#     - yarn stylelint

# test:
#   stage: test
#   script:
#     - yarn test

pages:
  stage: deploy
  variables: 
    PUBLIC_URL: https://aliaksei.dzemyanovich.gitlab.io/anya_portfolio/
  script:
  - yarn
  - yarn build-prod
  - mv dist_prod public
 # - yarn run-pages
 # - mkdir .public
 # - cp -r * .public
 # - cp -r dist_prod .public
 # - mv .public public
  artifacts:
    paths:
    - public
