image: node:latest

stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build-prod
  artifacts:
    paths:
    - dist_preprod
    - dist_prod

lint:
  stage: lint
  script:
    - yarn lint
  when: manual

stylelint:
  stage: lint
  script:
    - yarn stylelint
  when: manual

test:
  stage: test
  script:
    - yarn test-cover
  when: manual

deploy:
  stage: deploy
  script:
  - terraform apply
