image: node:14.21.1

stages:
  - build
  - test
  - plan
  - apply
  - destroy
  - e2e-setup
  - e2e

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  CYPRESS_IMAGE: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1

cache:
  paths:
    - node_modules
    - cache/Cypress

.build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install zip
    - yarn
    - yarn zip
  artifacts:
    paths:
    - dist_preprod
    - dist_prod
    - terragrunt/modules/lambda/lambda.zip
  # when: manual

build-preprod:
  extends:
    - .build
  script:
    - yarn build-preprod
  only:
    - develop

build-prod:
  extends:
    - .build
  script:
    - yarn build-prod
  only:
    - master

.test:
  stage: test
  when: manual

lint:
  extends:
    - .test
  script:
    - yarn lint

stylelint:
  extends:
    - .test
  script:
    - yarn stylelint

unit:
  extends:
    - .test
  script:
    - yarn test-cover

.plan:
  stage: plan
  image:
    name: alpine/terragrunt
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
    - terragrunt run-all plan --terragrunt-non-interactive
  when: manual

plan-preprod:
  extends:
    - .plan
  before_script:
    - cd terragrunt/live/preprod
  only:
    - develop

plan-prod:
  extends:
    - .plan
  before_script:
    - cd terragrunt/live/prod
  only:
    - master

.apply:
  stage: apply
  image:
    name: alpine/terragrunt
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terragrunt run-all apply --terragrunt-non-interactive
  # when: manual

apply-preprod:
  extends:
    - .apply
  before_script:
    - cd terragrunt/live/preprod
  only:
    - develop

apply-prod:
  extends:
    - .apply
  before_script:
    - cd terragrunt/live/prod
  only:
    - master

# commented out for safete needs, comment out only if required
# .destroy:
#   stage: destroy
#   image:
#     name: alpine/terragrunt
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
#   script:
#     - terragrunt run-all destroy --terragrunt-non-interactive
#   when: manual

# destroy-preprod:
#   extends:
#     - .destroy
#   before_script:
#     - cd terragrunt/live/preprod
#   when: manual
#   only:
#     - develop

# destroy-prod:
#   extends:
#     - .destroy
#   before_script:
#     - cd terragrunt/live/prod
#   when: manual
#   only:
#     - master

e2e-setup:
  image: $CYPRESS_IMAGE
  stage: e2e-setup
  script:
    - yarn
  when: manual

.e2e:
  image: $CYPRESS_IMAGE
  stage: e2e
  when: manual

e2e-preprod:
  extends:
    - .e2e
  script:
    - yarn cy-preprod
  only:
    - develop

e2e-prod:
  extends:
    - .e2e
  script:
    - yarn cy-prod
  only:
    - master

integration-preprod:
  extends:
    - .e2e
  script:
    - yarn integration-preprod
  only:
    - develop

integration-prod:
  extends:
    - .e2e
  script:
    - yarn integration-prod
  only:
    - master
