image: node:latest

stages:
  - build
  - zip
  - test
  - init
  - plan
  - apply

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build-prod
    # - yarn zip # todo: zip cannot be found
  artifacts:
    paths:
    - dist_preprod
    - dist_prod
    # - terraform/lambda.zip

zip:
  stage: zip
  script:
    - apt-get update
    - apt-get install zip unzip
  when: manual

lint:
  stage: test
  script:
    - yarn lint
  when: manual

stylelint:
  stage: test
  script:
    - yarn stylelint
  when: manual

test:
  stage: test
  script:
    - yarn test-cover
  when: manual

init:
  stage: init
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform init -migrate-state
  artifacts:
    paths:
    - terraform/.terraform
    - terraform/.terraform.lock.hcl

plan:
  stage: plan
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform plan
  when: manual

apply:
  stage: apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform apply -auto-approve -lock=false
