image: node:latest

stages:
  - build
  - test
  - init
  - plan
  - apply
  - e2e-setup
  - e2e

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  CYPRESS_IMAGE: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1

cache:
  paths:
    - node_modules
    - cache/Cypress

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install zip
  script:
    - yarn
    - yarn build-preprod
    - yarn build-prod
    - yarn zip
  artifacts:
    paths:
    - dist_preprod
    - dist_prod
    - terraform/lambda.zip
  # when: manual

lint:
  stage: test
  script:
    - yarn lint
  # when: manual

stylelint:
  stage: test
  script:
    - yarn stylelint
  # when: manual

test:
  stage: test
  script:
    - yarn test-cover
  # when: manual

init:
  stage: init
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
    - cd terraform
    - terraform init -migrate-state
  artifacts:
    paths:
    - terraform/.terraform
    - terraform/.terraform.lock.hcl
  # when: manual

plan:
  stage: plan
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
    - cd terraform
    - terraform plan
  when: manual

apply:
  stage: apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
    - cd terraform
    - terraform apply -auto-approve -lock=false
  # when: manual

e2e-setup:
  image: $CYPRESS_IMAGE
  stage: e2e-setup
  script:
    - yarn # todo: do not run yarn here, re-use 'build' stage

e2e-dev:
  image: $CYPRESS_IMAGE
  stage: e2e
  script:
    - yarn cy-dev

e2e-preprod:
  image: $CYPRESS_IMAGE
  stage: e2e
  script:
    - yarn cy-preprod
  when: manual

e2e-prod:
  image: $CYPRESS_IMAGE
  stage: e2e
  script:
    - yarn cy-prod
  when: manual
