image: node:latest

stages:
  - build
  - test
  - init
  - plan
  - apply
  - e2e

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  paths:
    - node_modules
    - cache/Cypress

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install zip
  script:
    - yarn
    - yarn build-preprod
    - yarn build-prod
    - yarn zip
  artifacts:
    paths:
    - dist_preprod
    - dist_prod
    - terraform/lambda.zip

lint:
  stage: test
  script:
    - yarn lint
  when: manual

stylelint:
  stage: test
  script:
    - yarn stylelint
  when: manual

test:
  stage: test
  script:
    - yarn test-cover
  when: manual

init:
  stage: init
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform init -migrate-state
  artifacts:
    paths:
    - terraform/.terraform
    - terraform/.terraform.lock.hcl
  when: manual

plan:
  stage: plan
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform plan
  when: manual

apply:
  stage: apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  script:
  - cd terraform
  - terraform apply -auto-approve -lock=false
  when: manual

e2e-dev:
  image: cypress/base:latest
  stage: e2e
  script:
    - yarn cy-dev

e2e-preprod:
  stage: e2e
  script:
    - yarn cy-preprod
  when: manual

e2e-prod:
  stage: e2e
  script:
    - yarn cy-prod
  when: manual
