image: node:14.21.1

stages:
  - build
  - test
  - plan
  - apply
  - destroy
  - e2e

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  CYPRESS_IMAGE: cypress/browsers:node-18.14.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1

cache:
  paths:
    - node_modules
    - cache/Cypress

.build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install zip
    - yarn
    - yarn zip
  artifacts:
    paths:
    - dist_preprod
    - dist_prod
    - terragrunt/modules/lambda/lambda.zip

build-preprod:
  extends:
    - .build
  script:
    - yarn build-preprod
  only:
    - develop

build-prod:
  extends:
    - .build
  script:
    - yarn build-prod
  only:
    - master

lint:
  stage: test
  script:
    - yarn lint

stylelint:
  stage: test
  script:
    - yarn stylelint

test:
  stage: test
  script:
    - yarn test-cover

.plan:
  stage: plan
  image:
    name: alpine/terragrunt
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  when: manual

plan-preprod:
  extends:
    - .plan
  script:
    - cd terragrunt/live/preprod
    - terragrunt run-all plan --terragrunt-non-interactive
  only:
    - develop

plan-prod:
  extends:
    - .plan
  script:
    - cd terragrunt/live/prod
    - terragrunt run-all plan --terragrunt-non-interactive
  only:
    - master

.apply:
  stage: apply
  image:
    name: alpine/terragrunt
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  

apply-preprod:
  extends:
    - .apply
  script:
    - cd terragrunt/live/preprod
    - terragrunt run-all apply --terragrunt-non-interactive
  only:
    - develop

apply-prod:
  extends:
    - .apply
  script:
    - cd terragrunt/live/prod
    - terragrunt run-all apply --terragrunt-non-interactive
  only:
    - master

.destroy:
  stage: destroy
  image:
    name: alpine/terragrunt
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  when: manual

destroy-preprod:
   extends:
    - .destroy
  script:
    - cd terragrunt/live/preprod
    - terragrunt run-all destroy --terragrunt-non-interactive
  when: manual
  only:
    - develop

destroy-prod:
  extends:
    - .destroy
  script:
    - cd terragrunt/live/prod
    - terragrunt run-all destroy --terragrunt-non-interactive
  when: manual
  only:
    - master

.e2e:
  image: $CYPRESS_IMAGE
  stage: e2e
  before_script:
    - yarn
  when: manual

e2e-preprod:
  extends:
    - .e2e
  script:
    - yarn cy-preprod
  only:
    - develop

e2e-prod:
  extends:
    - .e2e
  script:
    - yarn cy-prod
  only:
    - master
